### Генерация случайной матрицы

Сгенерируйте матрицу, состоящую из 1000 строк и 50 столбцов, элементы которой являются случайными из нормального распределения N(1,100).

Функция для генерации чисел из нормального распределения: np.random.normal

Параметры:

loc: среднее нормального распределения (в нашем случае 1)
scale: стандартное отклонение нормального распределения (в нашем случае 10)
size: размер матрицы (в нашем случае (1000, 50))

In [1]:
import numpy as np
X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print(X)

[[  9.66026592   4.54521814  -0.8524299  ...  12.73180644  -0.91389915
   12.95730127]
 [ -6.90259322   7.97767456  11.9859274  ...  -2.61085358  -6.28157631
   -5.18266294]
 [ 14.50267366 -14.68387844  12.53162822 ...  -0.12792636   3.54176372
    1.55409196]
 ...
 [  2.07498871 -12.14008313  18.24285204 ...   6.72943611  -1.80261367
   17.37940394]
 [  9.67724293  -6.40485089  21.47035914 ...  -6.40289506  -1.27081183
    0.0249052 ]
 [ -7.78897785  -0.6285909  -17.51565799 ...   6.10582615  -2.78246858
   19.22428481]]


### Нормировка матрицы

Произведите нормировку матрицы из предыдущего задания: вычтите из каждого столбца его среднее значение, а затем поделите на его стандартное отклонение.

Функция для вычисления среднего: np.mean

Функция для вычисления стандартного отклонения: np.std

Первый параметр — матрица, для которой производятся вычисления. Также полезным будет параметр axis, который указывает, по какому измерению вычисляются среднее и стандартное отклонение (если axis=0, то по столбцам, если axis=1, то по строкам; если его не указывать, то данные величины будут вычислены по всей матрице).

In [5]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m)  / std)
print (X_norm)

[[-0.10299753  1.08738961  0.33322945 ...  1.09418867 -1.31477484
  -1.46868467]
 [-0.11918681  0.00989625 -1.73272188 ...  0.72672319  0.40691598
  -1.57732601]
 [-0.075167    0.58536235  0.39900589 ...  0.33287608  0.0348073
   1.28677806]
 ...
 [ 1.65085766  0.75051396 -0.1561075  ... -0.95389152  1.32781968
   0.38022633]
 [ 0.90188557  1.16212533 -0.21213708 ...  0.95513987 -1.11232055
   1.17584343]
 [ 0.5644514   1.96774998 -0.7964888  ... -0.0067712   1.49540264
  -0.72751575]]


### Операции над элементами матрицы

Выведите для заданной матрицы номера строк, сумма элементов в которых превосходит 10.

Функция для подсчета суммы: np.sum

Аргументы аналогичны функциям np.mean и np.std.

К матрицам можно применять логические операции, которые будут применяться поэлементно. Соответственно, результатом такой операции будет матрица такого же размера, в ячейках которой будет записано либо True, либо False. Индексы элементов со значением True можно получить с помощью функции np.nonzero.

In [2]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])
r = np.sum(Z, axis=1)
print(r)
print (np.nonzero(r > 10))

[ 9 13  7  9 27 12]
(array([1, 4, 5], dtype=int64),)


### Объединение матриц

Сгенерируйте две единичные матрицы (т.е. с единицами на диагонали) размера 3x3. Соедините две матрицы в одну размера 6x3.

Функция для генерации единичной матрицы: np.eye

Аргумент: число строк (или, что эквивалентно, столбцов).

Функция для вертикальной стыковки матриц: np.vstack((A, B))

In [6]:
A = np.eye(3)
B = np.eye(3)
print (A)
print (B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
AB = np.vstack((A, B))
print (AB)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
